### ISSUE TITLE
how can i use it in my project?

### ISSUE THREAD

**Issue by john1923** [rmmoul/php-aes-class#1]
i just trying to make upload file using auto encrypted with aes when upload, and auto decrypted when downlod from the server,and the key is password user who was logon, the idea is to secure the file in the server from un autorizide user.
here i already success to make file upload to the server, but no auto encrypted file, so i want to use your code to make it work with the idea, but i just confused how to use your code in my project, could you help me?

here my upload.php

```
 <?php

 include_once 'dbconfig.php';   //koneksi dengan database
 session_start();

if($_SESSION['user'] and ($_SESSION['nik'])){
}
else{ 
   header("location:index.php");
}


if(isset($_POST['btn-upload']))

    $file       =rand(1000,100000)."-".$_FILES['file']['name'];
    $file_loc   =$_FILES['file']['tmp_name'];
    $file_size  =$_FILES['file']['size'];
    $dekripsi   =$_POST['dekripsi'];
    $file_type  =$_FILES['file']['type'];
    $file_nik   = $_SESSION ['nik'];
    $file_namalengkap = $_SESSION ['user'];
    $folder="uploads/";
    $new_size = $file_size/1024;  
    $new_file_name = strtolower($file);
    $final_file=str_replace(' ','-',$new_file_name);

    if (move_uploaded_file($file_loc,$folder.$final_file)){
        $sql="INSERT INTO tbl_uploads(file,namalengkap,nik,dekripsi,type,size) VALUES('$final_file','".$_SESSION ['user']."','".$_SESSION ['nik']."','$dekripsi','$file_type','$new_size')";
        mysql_query($sql);
        echo mysql_error();

        ?>
            <script>
                alert('successfully uploaded');
                window.location.href='home.php?success';
            </script>
        <?php

    }
    else
    {
        ?>
            <script>
                alert('gagal upload');
                window.location.href='home.php?fail';
            </script>
        <?php
    }
 ?>`
```

**Comment by rmmoul** [comment]
I'm not seeing any attempt to use the aes code at all. Have you tried using it / following the instructions in the readme?

You're going to need to include the class, set the key to the user's password (and set the iv, which you'll need to store for each file you encrypt), then you pass the file path to the encrypt_file method along with the filename/path to use for saving the encrypted file. 

Once you've tried what's in the readme, let me know if you have any specific problems / errors.

**Comment by john1923** [comment]
iam so sorry but iam newbie, and iam little bad at english, 
i get this error when i put the code like that, 

`Notice: Undefined variable: file in C:\xampp\htdocs\aes\uploadaes.php on line 22
Notice: Undefined variable: file in C:\xampp\htdocs\aes\uploadaes.php on line 22

Fatal error: Uncaught exception 'Exception' with message 'Could not open input file' in C:\xampp\htdocs\aes\aes.php:45 Stack trace: #0 C:\xampp\htdocs\aes\uploadaes.php(22): aes_encryption->encrypt_file(NULL, '.enc') #1 {main} thrown in C:\xampp\htdocs\aes\aes.php on line 45`

![sasa](https://cloud.githubusercontent.com/assets/15333849/10750184/e5ca47be-7ca4-11e5-9052-b353431bfa0f.png)

**Comment by rmmoul** [comment]
The encrypt_file method needs to be given a file to encrypt, but you're calling it at the top of your file with an undefined variable. You need to get the uploaded file's path to pass to the method for encryption, so you'll want to call that lower in your script and feed it the uploaded file's path.

**Comment by john1923** [comment]
oh yeah i got it, i already put the encypt method below the query. and still shows error like this, 

Fatal error: Uncaught exception 'Exception' with message 'Could not open input file' in C:\xampp\htdocs\aes\aes.php:45 Stack trace: #0 C:\xampp\htdocs\aes\uploadaes.php(42): aes_encryption->encrypt_file('67286-2012-1-00...', '67286-2012-1-00...') #1 {main} thrown in C:\xampp\htdocs\aes\aes.php on line 45

**Comment by john1923** [comment]
after trial n error, it should be work, but it show error that i can understand,

Fatal error: Call to undefined function openssl_random_pseudo_bytes() in C:\wamp\www\file-process\aes.php on line 20

how can fix that?
